services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
    image: fe-toanehihi
    container_name: fe
    ports:
      - "3000:80"
    restart: always
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge
