server {
    listen 80;
    server_name toanehihi.io.vn;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        add_header Content-Security-Policy "upgrade-insecure-requests";
    }
}

# SSL Configuration (To be enabled after generating certs)
# server {
#     listen 443 ssl;
#     server_name toanehihi.io.vn;
#     ssl_certificate /etc/letsencrypt/live/toanehihi.io.vn/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/toanehihi.io.vn/privkey.pem;
#     location / {
#         proxy_pass http://localhost:3000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }
